# Generates Makefile.3ds for the dRally-3ds branch.
#
# It reuses the object lists from the upstream Makefile verbatim (no hand-typed 300+ names) and
# wraps them into a devkitPro/3DS build:
#   * devkitARM + libctru via $(DEVKITARM)/3ds_rules
#   * SDL2 with its native n3ds backend, built from source (see doc/3ds.md)
#   * platform_3ds/dr3_input.c (pad -> keyboard scancodes) and the inert SDL_net stub
#
#   powershell -ExecutionPolicy Bypass -File scripts\gen_makefile_3ds.ps1
param(
    [string]$Repo = (Get-Item (Join-Path $PSScriptRoot '..\..')).FullName   # the repository root
)

$ErrorActionPreference = 'Stop'

$makefile = Join-Path $Repo 'Makefile'
$src      = Get-Content $makefile -Raw

$marker   = 'OBJS := data.o bss.o'
$startIdx = $src.IndexOf($marker)
if ($startIdx -lt 0) { throw "marker '$marker' not found in Makefile" }

$tailMarker = 'UNI_OBJS := drally.o drencryption.o'
$endIdx     = $src.IndexOf($tailMarker)
if ($endIdx -lt 0) { throw "marker '$tailMarker' not found in Makefile" }

$lists = $src.Substring($startIdx, ($endIdx - $startIdx) + $tailMarker.Length)
$lists = $lists.TrimEnd() + "`n"

$header = @'
#---------------------------------------------------------------------------------
# dRally - Nintendo 3DS build.
#
# GENERATED by scripts/gen_makefile_3ds.ps1 - the object lists below are copied verbatim from the
# upstream Makefile, so this build compiles exactly the same sources as the working Windows/Vita/
# Switch builds. Re-run the generator after pulling upstream changes.
#
# Requirements
#   * devkitPro with devkitARM + 3ds-dev (libctru), including tools\bin (3dsxtool) on PATH
#   * SDL2 built for the 3DS from source - SDL2 has a native n3ds backend, but devkitPro does not
#     package SDL2 for the 3DS (only SDL 1.2), see doc/3ds.md for the cmake lines
#   * GNU make, running in the devkitPro MSYS2 environment
#
# Usage
#   export DEVKITPRO=/opt/devkitpro
#   make -f Makefile.3ds -j4                       # -> build/3ds/dRally_3ds.3dsx
#   make -f Makefile.3ds -j4 DR3_DEBUG=1           # -> build/3ds_debug/dRally_3ds_debug.3dsx (profiler)
#
# Notes
#   * only SDL2's software renderer exists on the 3DS (framebuffer driver)
#   * SDL2main is linked so ROMFS is enabled
#   * SDL_net is not available for the 3DS: platform_3ds/sdl2_net_stub is used instead, which keeps
#     the multiplayer code compiling and linking (it just cannot connect)
#---------------------------------------------------------------------------------
ifeq ($(strip $(DEVKITARM)),)
$(error "Please set DEVKITARM in your environment, e.g. export DEVKITARM=$$DEVKITPRO/devkitARM")
endif

ifeq ($(strip $(DEVKITPRO)),)
$(error "Please set DEVKITPRO in your environment (devkitPro install path)")
endif

# The upstream Makefile's header (CC := gcc etc.) is NOT copied by the generator - only the object
# lists are - so the toolchain has to be defined here.
PREFIX ?= arm-none-eabi-
CC     := $(PREFIX)gcc

# where SDL2 for the 3DS was installed (cmake --install prefix)
SDL2_3DS_PREFIX ?= $(DEVKITPRO)/portlibs/3ds
SDL2_3DS_LIB    ?= $(SDL2_3DS_PREFIX)/lib

TARGET   := dRally_3ds
BUILD    := build/3ds
CTRULIB  ?= $(DEVKITPRO)/libctru
LIBDIRS  := -L$(SDL2_3DS_LIB) -L$(CTRULIB)/lib

# DR_MULTIPLAYER/IPXNET are kept: menus, race code and the chat box reference multiplayer symbols
# unconditionally (verified: dropping them produces 20 unresolved externals on Windows/MSVC).
DEFINES  := -D__3DS__ -DDR_LETTERBOX -DDR_MULTIPLAYER -DIPXNET -DDR3_LOG_KEYS -DDR3_USE_GFX

# Profiling build (platform_3ds/dr3_prof.h):   make -f Makefile.3ds DR3_DEBUG=1
# It measures the frame budget, rotates measurement variants on its own and writes the results to
# sdmc:/drally_3ds.log.  It gets its own object tree, so the release and debug builds never
# recompile (or link) each other's objects.
DR3_DEBUG ?= 0
ifeq ($(DR3_DEBUG),1)
BUILD    := build/3ds_debug
TARGET   := dRally_3ds_debug
DEFINES  += -DDR3_PROFILE
APP_TITLE := dRally 3DS (profile)
endif

OUTPUT   := $(BUILD)/$(TARGET)

INCLUDES := -I$(CURDIR) \
            -I$(CURDIR)/platform_3ds \
            -I$(CURDIR)/platform_3ds/sdl2_net_stub/include \
            -I$(SDL2_3DS_PREFIX)/include \
            -I$(SDL2_3DS_PREFIX)/include/SDL2 \
            -I$(DEVKITPRO)/libctru/include

# GCC 14+ promoted several historical warnings to errors (incompatible pointer types, implicit
# function declarations, ...). This DOS-era decompiled code relies on the old lenient behaviour --
# the PS Vita/Switch builds used an older GCC and never saw these.  Downgrade them back to warnings.
LEGACY_WARNINGS := -Wno-error=incompatible-pointer-types \
                   -Wno-error=int-conversion \
                   -Wno-error=implicit-function-declaration \
                   -Wno-error=implicit-int \
                   -Wno-error=return-mismatch

# NOTE: keep the "-DDR_LETTERBOX" scaling path; on the 3DS the engine draws into a 320x240 buffer
# which SDL scales to the 400x240 top screen (see doc/3ds.md).
CFLAGS   := -g -Wall -O2 -D__3DS__ $(DEFINES) $(INCLUDES) \
            -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft \
            -ffunction-sections -fdata-sections -fno-common -MMD -MP $(LEGACY_WARNINGS)

LDFLAGS  := -g -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft \
            -specs=3dsx.specs -Wl,-Map,$(OUTPUT).map -Wl,--gc-sections

LIBS     := -lSDL2main -lSDL2 -lctru -lm

EXTRA_OBJS := platform_3ds/dr3_input.o \
              platform_3ds/dr3_input_map.o \
              platform_3ds/dr3_blit.o \
              platform_3ds/dr3_log.o \
              platform_3ds/dr3_paths.o \
              platform_3ds/dr3_fb.o \
              platform_3ds/dr3_prof.o \
              platform_3ds/dr3_bottom.o \
              platform_3ds/sdl2_net_stub/sdl2_net_stub.o

'@

$footer = @'

ALL_OBJS := $(addprefix $(BUILD)/, $(UNI_OBJS) $(LINUX_OBJS) $(RACE_OBJS) $(MENU_OBJS) \
              $(SHOP_OBJS) $(UNDERGROUND_OBJS) $(OBJS) $(MP_CMN_OBJS) $(MP_OBJS) $(DFR_OBJS)) \
            $(addprefix $(BUILD)/, $(EXTRA_OBJS))

.PHONY: all clean

# home screen metadata (icon + title shown by the Homebrew Launcher)
APP_TITLE   ?= dRally 3DS
APP_DESC    := Death Rally (1996) engine port
APP_AUTHOR  := urxp / dRally, 3DS port
APP_ICON    ?= $(CTRULIB)/default_icon.png

all: $(OUTPUT).3dsx

# NOTE: this makefile is deliberately self contained and does NOT include $(DEVKITARM)/3ds_rules -
# that file brings its own %.elf/%.3dsx rules and variable conventions which would conflict with the
# explicit object lists above.  3dsxtool does the .elf -> .3dsx conversion here.
$(OUTPUT).smdh: $(APP_ICON) Makefile.3ds
	@echo "  SMDH   $(notdir $@)"
	@smdhtool --create "$(APP_TITLE)" "$(APP_DESC)" "$(APP_AUTHOR)" $(APP_ICON) $@

$(OUTPUT).3dsx: $(OUTPUT).elf $(OUTPUT).smdh
	@echo "  TOOL   3dsxtool $@"
	@3dsxtool $< $@ --smdh=$(OUTPUT).smdh

$(OUTPUT).elf: $(ALL_OBJS)
	@echo "  LINK   $(notdir $@)"
	@$(CC) $(ALL_OBJS) $(LIBDIRS) $(LIBS) $(LDFLAGS) -o $@

$(BUILD)/%.o: %.c
	@mkdir -p $(@D)
	@echo "  CC     $<"
	@$(CC) -c $(CFLAGS) $< -o $@

clean:
	@rm -rf $(BUILD)

-include $(ALL_OBJS:.o=.d)
'@

$out = Join-Path $Repo 'Makefile.3ds'
Set-Content -Path $out -Value ($header + $lists + $footer) -Encoding UTF8

$lines = (Get-Content $out | Measure-Object -Line).Lines
Write-Host "wrote $out ($lines lines)"
